### ISSUE TITLE
[BUG]: Not all backups are created the same. "hidden files"

### ISSUE THREAD

**Issue by Will-wastelander** [jneilliii/OctoPrint-BackupScheduler#24]
**Describe the bug**
Not all backups are not created. Some backups appear to be hidden. This is due to the naming scheme that gets applied to them. The names some how get a . in front of them.

**Expected behavior**
Backup names to not have their names start with .

**Debug Log**
I will work on getting debug logs.

-- Redacted config.yaml -- Original sent in discord channel.
  backupscheduler:
    daily:
      enabled: true
      retention: '14'
    daily_backups:
    - octoprint-daily-20220404-000012.zip
    monthly:
      enabled: true
      retention: '12'
    monthly_backups:
    - octoprint-monthly-20211201-000021.zip
    startup:
      enabled: true
    startup_backups:
    - octoprint-startup-20220422-125126.zip
    weekly:
      day: '7'
      enabled: true
      retention: '8'
    weekly_backups:
    - octoprint-weekly-20220206-000049.zip

**Screenshots**
Sent on discord

**Firmware and Version**
Happens on Marlin, and Prusa that I can see so far.

**Comment by Will-wastelander** [comment]
2022-04-24 00:00:35,550 - octoprint.plugins.backupscheduler - DEBUG - Performing daily_backups with exclusions: [] as octoprint-daily-20220424-000035.zip.
2022-04-24 00:00:35,555 - octoprint.plugins.backupscheduler - DEBUG - Deleting backups: ['octoprint-daily-20220405-000013.zip']
2022-04-24 00:00:35,841 - octoprint.plugins.backupscheduler - DEBUG - ['octoprint-daily-20220406-000014.zip', 'octoprint-daily-20220407-000015.zip', 'octoprint-daily-20220408-000016.zip', 'octoprint-daily-20220409-000017.zip', 'octoprint-daily-20220410-000018.zip', 'octoprint-daily-20220411-000019.zip', 'octoprint-daily-20220412-000020.zip', 'octoprint-daily-20220413-000021.zip', 'octoprint-daily-20220414-000045.zip', 'octoprint-daily-20220415-000055.zip', 'octoprint-daily-20220417-000011.zip', 'octoprint-daily-20220420-191200.zip', 'octoprint-daily-20220423-000008.zip', 'octoprint-daily-20220424-000035.zip']
2022-04-24 00:00:35,843 - octoprint.plugins.backupscheduler - DEBUG - Performing weekly_backups with exclusions: [] as octoprint-weekly-20220424-000035.zip.
2022-04-24 00:00:35,846 - octoprint.plugins.backupscheduler - DEBUG - Deleting backups: ['octoprint-weekly-20220206-000049.zip']
2022-04-24 00:00:35,853 - octoprint.plugins.backup - ERROR - Error while creating backup zip
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/plugins/backup/__init__.py", line 1006, in _create_backup
    raise InsufficientSpace()
octoprint.plugins.backup.InsufficientSpace
2022-04-24 00:00:36,101 - octoprint.plugins.backupscheduler - DEBUG - ['octoprint-weekly-20220227-151028.zip', 'octoprint-weekly-20220306-000036.zip', 'octoprint-weekly-20220313-000045.zip', 'octoprint-weekly-20220327-000043.zip', 'octoprint-weekly-20220403-000041.zip', 'octoprint-weekly-20220410-000018.zip', 'octoprint-weekly-20220417-000011.zip', 'octoprint-weekly-20220424-000035.zip']
2022-04-24 00:00:36,113 - octoprint.plugins.backup - ERROR - Error while creating backup zip
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/plugins/backup/__init__.py", line 1006, in _create_backup
    raise InsufficientSpace()
octoprint.plugins.backup.InsufficientSpace

pi@octopi-prusa-mk3s:~ $ df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/root        30G   25G  3.3G  89% /
devtmpfs        1.7G     0  1.7G   0% /dev
tmpfs           1.9G   12K  1.9G   1% /dev/shm
tmpfs           1.9G   73M  1.8G   4% /run
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           1.9G     0  1.9G   0% /sys/fs/cgroup
/dev/mmcblk0p1  253M   49M  204M  20% /boot
tmpfs           379M     0  379M   0% /run/user/1000

**Comment by Will-wastelander** [comment]
Is there any update on this bug ?
